#! /usr/bin/env python3.10

import shlex
import shutil
import argparse
import pandas as pd
from os import system
from os import getuid
from sys import stdout
from pwd import getpwuid
from subprocess import Popen, PIPE

username = getpwuid(getuid())[0]

# Set Default Number of Files to Edit
default_number = 3

aparser = argparse.ArgumentParser()
add_arg = aparser.add_argument
add_arg("-n", "--number", required=False)
args = aparser.parse_args()
number = args.number
df = pd.read_csv("~/repos/journal/sites.csv", delimiter="|")
df = df.applymap(lambda x: x.strip())
df.columns = [x.strip() for x in df.columns]
if number == None:
    df = df.head(default_number)
elif number.isnumeric():
    number = int(number)
    if number > df.shape[0]:
        number = df.shape[0]
    df = df.head(number)
    print('hit')

alist = df[['path']].values.tolist()
journals = " ".join([f'~/{x[0]}/journal.md' for x in alist])
edit_journals = f"vim {journals} ~/.vimrc"
system(edit_journals)


def flush(std):
    for line in std:
        line = line.strip()
        if line:
            print(line)
            stdout.flush()


def git(cwd, args):
    cmd = ["/usr/bin/git"] + shlex.split(args)
    print(f"COMMAND: << {shlex.join(cmd)} >>")
    process = Popen(
        args=cmd,
        cwd=cwd,
        stdout=PIPE,
        stderr=PIPE,
        shell=False,
        bufsize=1,
        universal_newlines=True,
    )
    flush(process.stdout)
    flush(process.stderr)


shutil.copyfile(f"/home/{username}/.screenrc", "/home/{username}/repos/vim/.screenrc")
shutil.copyfile(f"/home/{username}/.gitconfig", "/home/{username}/repos/vim/.gitconfig")
shutil.copyfile(f"/home/{username}/.bash_prompt", "/home/{username}/repos/vim/.bash_prompt")
shutil.copyfile(f"/home/{username}/.bash_profile", "/home/{username}/repos/vim/.bash_profile")
shutil.copyfile(f"/usr/local/sbin/all", "/home/{username}/repos/vim/all")

print()
print("GIT VIM")
loc = f"/home/{username}/repos/vim"
git(loc, 'commit -am "Pushing vim to Github..."')
git(loc, "push")

print()
print("GIT JOURNAL")
loc = f"/home/{username}/repos/journal"
git(loc, 'commit -am "Pushing journal to Github..."')
git(loc, "push")

print()
print("GIT MIKELEV.IN")
loc = f"/home/{username}/repos/MikeLev.in"
git(loc, 'commit -am "Pushing blog to Github..."')
git(loc, "push")

print("Done!")
